### ISSUE TITLE
Susi Fbbot not set up

### ISSUE THREAD

**Issue by Manveer695** [fossasia/susi_fbbot#14]
Looks like the fbbot (I am testing it from [here](https://www.facebook.com/asksusisu/)) is not currently set up and we don't have access to the susi_fbbot account.

Screenshot (No replies to the messages):
<img width="196" alt="asksusifb" src="https://user-images.githubusercontent.com/20307535/27779532-483dcdaa-5fe1-11e7-804b-a1e8785ef779.PNG">

@shivenmian Could you share the account login please by an email to the mentors or to me here: singhmanveer1995@gmail.com?

Also, if I am testing the wrong page on FB please let me know.
Thank you.

**Comment by shivenmian** [comment]
@sudheesh001 has the account login, please ask him.

**Comment by Manveer695** [comment]
@shivenmian Ok Thanks. Also, am I testing the right page?

**Comment by chiragw15** [comment]
No. Actually that's my page. I made Susi fb bot some time ago.

**Comment by shivenmian** [comment]
Sudheesh had also set up an FB Bot.

**Comment by Manveer695** [comment]
@chiragw15 I think you are visiting susi test page and not a ask susi page. Visit the link mentioned above please.

**Comment by Manveer695** [comment]
@sudheesh001 sir, please if you could share the susi fbbot account link. Thank you.

**Comment by chiragw15** [comment]
Yup. 'SusiTest' page is mine and not 'Ask Susi'. I got a message from you on it that's why I thought you are talking about it. :+1:

**Comment by Manveer695** [comment]
@chiragw15 Thanks for the clarification.

**Comment by Manveer695** [comment]
@sudheesh001 Please look into this issue sir. Thank you.

**Comment by sudheesh001** [comment]
Ask Susi is a page is public but the application for the bot to reply is restricted by the developers, do you want access to the developer application of the facebook app? Please message me on facebook for the same. fb.me/sudheesh001

**Comment by Manveer695** [comment]
It's set up now. Developers, admins, and testers can test it messaging [here](https://www.facebook.com/asksusisu/). Hence closing the issue.
