### ISSUE TITLE
Getting started guide missing

### ISSUE THREAD

**Issue by avirlrma** [fossasia/susi_fbbot#59]
**Actual Behaviour**
Getting started guide referred in the Readme is missing

**Expected Behaviour**
It should point to a getting started guide.

**Would you like to work on the issue?**
Yes,but I need help on setting it up.

**Comment by husainhz7** [comment]
I can fix this, can you please assign me.

**Comment by abishekvashok** [comment]
@aviral1701 this seems fixed in #60
